[theme]
theme = "solarized-dark"
[icons]
icons = "material-nf"

[[block]]
block = "net"
format_alt = " $ip "

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage {$time |}"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_used_percents.eng(w:1) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1

[[block]]
block = "temperature"
format = " $icon $average avg "
format_alt = " $icon $max max "

[[block]]
block = "sound"
max_vol = 200

[[block]]
block = "time"
interval = 5
